name: euchack
description: "A feature for Juniper"

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  fonts:
   - family: Alegreya
     fonts:
      - asset: assets/fonts/Alegreya-Regular.ttf
      - asset: assets/fonts/Alegreya-Black.ttf
      - asset: assets/fonts/Alegreya-BlackItalic.ttf
      - asset: assets/fonts/Alegreya-ExtraBold.ttf
      - asset: assets/fonts/Alegreya-ExtraBoldItalic.ttf
      - asset: assets/fonts/Alegreya-Italic-VariableFont_wght.ttf
      - asset: assets/fonts/Alegreya-Medium.ttf
      - asset: assets/fonts/Alegreya-MediumItalic.ttf
      - asset: assets/fonts/Alegreya-SemiBold.ttf
      - asset: assets/fonts/Alegreya-SemiBoldItalic.ttf
      - asset: assets/fonts/Alegreya-Bold.ttf
      - asset: assets/fonts/Alegreya-Italic.ttf
      - asset: assets/fonts/Alegreya-BoldItalic.ttf
    
   - family: IBM Plex Mono
     fonts:
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-BoldItalic.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLight.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLightItalic.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Italic.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Light.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-LightItalic.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Medium.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-MediumItalic.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-SemiBold.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Thin.ttf
      - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-ThinItalic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
